name: Notify Forked Users

on:
  pull_request:
    types:
      - closed  # Runs when a PR is closed (either merged or rejected)

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

            - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: "ambient963@gmail.com"
          password: "sxpv ujck ufze ugtr"
          subject: "🚀 Repo Update: Changes in Your Forked Repo"
          content_type: text/html
          body: |
            <!DOCTYPE html>
            <html>
            <head>
                <style>
                    body {
                        font-family: Arial, sans-serif;
                        background-color: #f4f4f4;
                        padding: 20px;
                    }
                    .container {
                        background: white;
                        padding: 20px;
                        border-radius: 10px;
                        box-shadow: 0px 0px 10px rgba(0,0,0,0.1);
                        max-width: 600px;
                        margin: auto;
                    }
                    h2 {
                        color: #333;
                    }
                    p {
                        color: #555;
                        font-size: 16px;
                    }
                    .cta-button {
                        background-color: #007BFF;
                        color: white;
                        padding: 10px 20px;
                        text-decoration: none;
                        border-radius: 5px;
                        display: inline-block;
                        margin-top: 15px;
                        font-weight: bold;
                    }
                    .footer {
                        margin-top: 20px;
                        font-size: 14px;
                        color: #888;
                        text-align: center;
                    }
                </style>
            </head>
            <body>
                <div class="container">
                    <h2>🚀 Repository Update Alert</h2>
                    <p>Hello Developer,</p>
                    <p>The repository you forked has been updated with new changes.</p>
                    <p>Click below to check out the latest updates:</p>
                    <a class="cta-button" href="https://github.com/abhxxshek/resume_builder_job_tracker.git" target="_blank">🔗 View Repository</a>
                    <p class="footer">Happy coding! 🚀</p>
                </div>
            </body>
            </html>

          to: |
            akhilzacharia.mail@gmail.com,
            aksassanthosh2002@gmail.com,
            anupmanil10@gmail.com,
            gokulsanthosh125@gmail.com
          from: "Abhishek"
